# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

# Collect flet_desktop data files (from flet-desktop-light package - lightweight Flutter engine without mpv)
flet_desktop_datas = collect_data_files('flet_desktop')

a = Analysis(
    ['nak-flet/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src', 'src'),
        ('nak-flet/assets', 'assets'),
    ] + flet_desktop_datas,
    hiddenimports=[
        'flet',
        'flet.auth',
        'flet.auth.providers',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'vdf',
        'psutil',
        'py7zr',
        'pillow',
        'PIL',
        'PIL.Image',
        'logging',
        'logging.handlers',
        'logging.config',
        'src.core.core',
        'src.core.dependency_installer',
        'src.core.unverum_installer',
        'src.core.dotnet9sdk_installer',
        'src.mod_managers.mo2.installer',
        'src.mod_managers.vortex.installer',
        'src.utils.steam_utils',
        'src.utils.game_utils',
        'src.utils.game_finder',
        'src.utils.comprehensive_game_manager',
        'src.utils.smart_prefix_manager',
        'src.utils.prefix_locator',
        'src.utils.settings_manager',
        'src.utils.logger',
        'src.utils.proton_tool_manager',
        'src.utils.dependency_cache_manager',
        'src.utils.utils',
        'src.utils.command_cache',
        'src.utils.proton_ge_manager',
        'src.utils.proton_finder',
        'src.utils.nak_paths',
        'src.utils.nak_storage_manager',
        'src.utils.nxm_handler_manager',
        'src.utils.launch_script_generator',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'libstdc++.so.6',
        'libgcc_s.so.1',
        'libssl.so.3',
        'libcrypto.so.3',
        'libglib-2.0.so',
        'libgobject-2.0.so',
        'libgio-2.0.so',
        'libgmodule-2.0.so',
        'libgthread-2.0.so',
        'libmount.so',
        'libblkid.so',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# Exclude problematic system libraries that conflict with newer systems
a.binaries = [x for x in a.binaries if not any(lib in x[0] for lib in [
    'libstdc++.so.6',
    'libgcc_s.so.1',
    'libssl.so.3',
    'libcrypto.so.3',
    'libglib-2.0.so',
    'libgobject-2.0.so',
    'libgio-2.0.so',
    'libgmodule-2.0.so',
    'libgthread-2.0.so',
    'libmount.so',
    'libblkid.so',
])]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='nak-modding-helper',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
