// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseForMO2Folder():Promise<string>;

export function CheckDependencies():Promise<main.CheckDependenciesResult>;

export function ConfigureNXMHandler(arg1:string,arg2:string):Promise<string>;

export function FindMO2():Promise<main.FindMO2Result>;

export function InstallMO2WithDirectory(arg1:string):Promise<string>;

export function LaunchMO2():Promise<string>;

export function RemoveNXMHandlers():Promise<string>;

export function ScanGames():Promise<main.ScanGamesResult>;

export function SelectDirectory():Promise<string>;

export function SetupExistingMO2(arg1:string,arg2:string):Promise<string>;

export function TestInstallMO2(arg1:string):Promise<string>;
