// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForMO2Folder() {
  return window['go']['main']['App']['BrowseForMO2Folder']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function ConfigureNXMHandler(arg1, arg2) {
  return window['go']['main']['App']['ConfigureNXMHandler'](arg1, arg2);
}

export function FindMO2() {
  return window['go']['main']['App']['FindMO2']();
}

export function InstallMO2(arg1) {
  return window['go']['main']['App']['InstallMO2'](arg1);
}

export function LaunchMO2() {
  return window['go']['main']['App']['LaunchMO2']();
}

export function RemoveNXMHandlers() {
  return window['go']['main']['App']['RemoveNXMHandlers']();
}

export function ScanGames() {
  return window['go']['main']['App']['ScanGames']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetupExistingMO2(arg1, arg2) {
  return window['go']['main']['App']['SetupExistingMO2'](arg1, arg2);
}

export function TestInstallMO2(arg1) {
  return window['go']['main']['App']['TestInstallMO2'](arg1);
}
